# Generated by Django 2.2.28 on 2024-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240425_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='bee.png', upload_to='profile_images'),
        ),
    ]
